blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/NetBr3ak/forge-grid/discussions
    about: Ask questions and discuss ideas
  - name: ðŸ“– Documentation
    url: https://github.com/NetBr3ak/forge-grid#readme
    about: Check out our documentation
