blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/NetBr3ak/internal-machine-monitor/discussions
    about: Ask questions and discuss ideas
  - name: ðŸ“– Documentation
    url: https://github.com/NetBr3ak/internal-machine-monitor#readme
    about: Check out our documentation
